# stores the multiplication tables generated by problem 3 in a file named "Table.txt"

n = int(input("Enter a number of multiplication table: "))

mult = [i * n for i in range(1, 11)]

with open('Table.txt', 'a') as f:
    for i, result in enumerate(mult, 1):
        f.write(f'{n} x {i} = {result}\n')
      
